beefit/urls.py
from django.urls import include, path, re_path
from rest_framework.routers import DefaultRouter

from beefit.api import *
from beefit.views import IndexView, ProgramsView, PhotosView, RulesView


router = DefaultRouter()
router.register(r'pages', PageViewSet)
router.register(r'contacts', ContactViewSet)
router.register(r'processes', ProcessViewSet)
router.register(r'pricings', PricingViewSet)
router.register(r'packages', PackageViewSet)
router.register(r'coaches', CoachViewSet)

urlpatterns = [
    path('api/', include(router.urls)),
    path('programs/', ProgramsView.as_view()),
    path('photos/', PhotosView.as_view()),
    path('rules/', RulesView.as_view()),
    re_path(r'(?P<path>.*)', IndexView.as_view()),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('djrichtextfield/', include('djrichtextfield.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Need to separate because beefit.urls will capture all other links aside from admin/
urlpatterns += [
    path('', include('beefit.urls')),
]

beefit/models.py
from django.db import models
from djrichtextfield.models import RichTextField

TIME_CHOICES = (
    (1, 'Month'),
    (2, '3 Months'),
    (3, '6 Months'),
    (4, 'Year'),
)


class Page(models.Model):
    header_text = models.CharField(max_length=150)
    header_subtext = models.CharField(max_length=50)
    footer_about = models.TextField(max_length=300)
    header_picture = models.ImageField(upload_to='headers')
    process_description = models.TextField(max_length=300, null=True, blank=True)
    programs_description = models.TextField(max_length=300, null=True, blank=True)
    packages_description = models.TextField(max_length=300, null=True, blank=True)
    location_description = models.TextField(max_length=300, null=True, blank=True)
    is_active = models.BooleanField(default=True)


class Contact(models.Model):
    number = models.CharField(max_length=15)
    is_active = models.BooleanField(default=True)
    page = models.ForeignKey('Page', on_delete=models.CASCADE)


class Process(models.Model):
    title = models.CharField(max_length=100)
    icon = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.title


class Program(models.Model):
    title = models.CharField(max_length=100)
    icon = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.title


class Pricing(models.Model):
    amount = models.FloatField()
    time_span = models.PositiveSmallIntegerField(choices=TIME_CHOICES)

    def __str__(self):
        time_span = dict(TIME_CHOICES)
        return "{} for {}".format(self.amount, time_span[self.time_span])


class Package(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    photo = models.ImageField(upload_to='packages')
    is_active = models.BooleanField(default=True)
    pricing_plans = models.ManyToManyField('Pricing')

    def __str__(self):
        return self.title


class Coach(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    position = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    photo = models.ImageField(upload_to='coaches')
    social_insta = models.CharField(max_length=200, null=True, blank=True)
    social_facebook = models.CharField(max_length=200, null=True, blank=True)
    social_twitter = models.CharField(max_length=200, null=True, blank=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return "{} {}".format(self.first_name, self.last_name)


class Photo(models.Model):
    description = models.CharField(max_length=255, null=True, blank=True)
    photo = models.ImageField(upload_to='photos')

    def __str__(self):
        return self.description


class Rule(models.Model):
    title = models.CharField(max_length=225, null=True, blank=True)
    rules = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.title

beefit/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView

from beefit.models import *


class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page'] = Page.objects.filter(is_active=True).last()
        context['processes'] = Process.objects.all()
        context['programs'] = Program.objects.all()[:3]
        context['coaches'] = Coach.objects.filter(is_active=True)
        context['packages'] = Package.objects.filter(is_active=True)
        context['gallery'] = Photo.objects.all()[:4]
        return context


class ProgramsView(TemplateView):
    template_name = 'programs.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['programs'] = Program.objects.all()
        return context


class PhotosView(TemplateView):
    template_name = 'photos.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['photos'] = Photo.objects.all()
        context['page'] = Page.objects.filter(is_active=True).last()
        return context


class RulesView(TemplateView):
    template_name = 'rules.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rules'] = Rule.objects.all()
        context['page'] = Page.objects.filter(is_active=True).last()
        return context

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>BeeFit</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800" rel="stylesheet">

  <link rel="stylesheet" href="{% static "css/open-iconic-bootstrap.min.css" %}">
  <link rel="stylesheet" href="{% static "css/animate.css" %}">

  <link rel="stylesheet" href="{% static "css/owl.carousel.min.css" %}">
  <link rel="stylesheet" href="{% static "css/owl.theme.default.min.css" %}">
  <link rel="stylesheet" href="{% static "css/aos.css" %}">
  <link rel="stylesheet" href="{% static "css/flaticon.css" %}">
  <link rel="stylesheet" href="{% static "css/icomoon.css" %}">
  <link rel="stylesheet" href="{% static "css/style.css" %}">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
      <a class="navbar-brand" href="/">BeeFit<small>Gym Plus</small></a>
      {% if request.path == "/" %}
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
          Menu
        </button>
        <div class="collapse navbar-collapse" id="ftco-nav">
          <ul class="navbar-nav ml-auto">
              <li class="nav-item"><a href="#process" class="nav-link">Process</a></li>
              <li class="nav-item"><a href="#programs" class="nav-link">Programs</a></li>
              <li class="nav-item"><a href="#coaches" class="nav-link">Coaches</a></li>
              <li class="nav-item"><a href="#packages" class="nav-link">Packages</a></li>
              <li class="nav-item"><a href="#footer" class="nav-link">Contact</a></li>
              <li class="nav-item"><a href="rules/" class="nav-link">Rules</a></li>
          </ul>
        </div>
      {% endif %}
    </div>
  </nav>

  {% block content %}
  {% endblock %}

  <script src="{% static "js/jquery.min.js" %}"></script>
  <script src="{% static "js/jquery-migrate-3.0.1.min.js" %}"></script>
  <script src="{% static "js/popper.min.js" %}"></script>
  <script src="{% static "js/bootstrap.min.js" %}"></script>
  <script src="{% static "js/jquery.easing.1.3.js" %}"></script>
  <script src="{% static "js/jquery.waypoints.min.js" %}"></script>
  <script src="{% static "js/jquery.stellar.min.js" %}"></script>
  <script src="{% static "js/owl.carousel.min.js" %}"></script>
  <script src="{% static "js/aos.js" %}"></script>
  <script src="{% static "js/scrollax.min.js" %}"></script>
  <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCYrK40tCS8cWQTbDWEiZFfhJhzMVWWWuU&callback=initMap"
  type="text/javascript"></script>
  <script src="{% static "js/google-map.js" %}"></script>
  <script src="{% static "js/main.js" %}"></script>

</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <section class="home-slider owl-carousel">
    <div class="slider-item" style="background-image: url({{ page.header_picture.url }})" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row slider-text justify-content-center align-items-center">
          <div class="col-md-8 col-sm-12 text-center ftco-animate">
            <h1 style="font-size: 40px;" class="mb-3 mt-5 bread">{{ page.header_text }}</h1>
            <p><span class="mr-2">{{ page.header_subtext }}</p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section class="ftco-section ftco-bg-dark" id="process">
    <div class="container">
      <div class="row justify-content-center mb-5">
        <div class="col-md-7 heading-section text-center ftco-animate">
          <span class="subheading">Services</span>
          <h2 class="mb-4">Our Process</h2>
          <p>{{ page.process_description }}</p>
        </div>
      </div>
      <div class="row">
        {% for process in processes %}
        <div class="col-md-3 ftco-animate">
          <div class="media d-block text-center block-6 services">
            <div class="icon d-flex justify-content-center align-items-center mb-5">
              <span class="flaticon-{{ process.icon }}"></span>
            </div>
            <div class="media-body">
              <h3 class="heading">{{ process.title }}</h3>
              <p>{{ process.description|linebreaksbr }}</p>
            </div>
          </div>      
        </div>
        {% endfor %}
      </div>
    </div>
  </section>

  <section class="ftco-section" id="programs">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-md-6 pr-md-5">
          <div class="heading-section text-md-right ftco-animate">
            <span class="subheading">Programs</span>
            <h2 class="mb-4">Fitness Programs</h2>
            <p class="mb-4">{{ page.programs_description }}</p>
          </div>
        </div>
        <div class="col-md-6">
          {% for program in programs %}
          <div class="program d-flex ftco-animate">
            <div class="icon d-flex justify-content-center align-items-center">
              <span class="flaticon-{{ program.icon }}"></span>
            </div>
            <div class="text ml-5">
              <h3>{{ program.title }}</h3>
              <p>{{ program.description|linebreaksbr }}</p>
            </div>
          </div>
          {% endfor %}
          <a href="/programs/">Click here for more...</a>
        </div>
      </div>
    </div>
  </section>

  <section class="ftco-section" id="coaches">
    <div class="container">
      <div class="row justify-content-center mb-5">
        <div class="col-md-7 heading-section text-center ftco-animate">
          <span class="subheading">Trainer</span>
          <h2 class="mb-4">Our Coaches</h2>
        </div>
      </div>
      <div class="row">
        {% for coach in coaches %}
        <div class="col-lg-6 d-flex">
          <div class="coach d-sm-flex align-items-stretch">
            <div class="img" style="background-image: url({{ coach.photo.url }})"></div>
            <div class="text py-4 px-5 ftco-animate">
              <span class="subheading">{{ coach.position }}</span>
              <h3><a href="#">{{ coach.first_name }} {{ coach.last_name }}</a></h3>
              <p>{{ coach.description|linebreaksbr }}</p>
              <ul class="ftco-social-media d-flex mt-4">
                {% if coach.social_twitter %}
                <li class="ftco-animate"><a href="{{ coach.social_twitter }}" class="mr-2 d-flex justify-content-center align-items-center"><span class="icon-twitter"></span></a></li>
                {% endif %}

                {% if coach.social_facebook %}
                <li class="ftco-animate"><a href="{{ coach.social_facebook }}" class="mr-2 d-flex justify-content-center align-items-center"><span class="icon-facebook"></span></a></li>
                {% endif %}

                {% if coach.social_insta %}
                <li class="ftco-animate"><a href="{{ coach.social_insta }}" class="mr-2 d-flex justify-content-center align-items-center"><span class="icon-instagram"></span></a></li>
                {% endif %}
              </ul>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </section>

  <section class="ftco-section" id="packages">
    <div class="container">
      <div class="row justify-content-center mb-5 pb-3">
        <div class="col-md-7 heading-section ftco-animate text-center">
          <h2 class="mb-4">Our Packages</h2>
          <p>{{ page.packages_description }}</p>
        </div>
      </div>
      <div class="row">
        {% for package in packages %}
        <div class="col-md-6 col-lg-4">
          <div class="package-program ftco-animate">
            <div class="img" style="background-image: url({{ package.photo.url }})"></div>
            <div class="text mt-4">
              <h3>{{ package.title }}</h3>
              {% for pricing in package.pricing_plans.all %}
              <div class="d-flex mt-4">
                <p class="price"><sup>PHP</sup>{{ pricing.amount }}<sub> / {{ pricing.get_time_span_display }}</sub></p>
              </div>
              {% endfor %}
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </section>

  <section class="ftco-section">
    <div class="container">
      <div class="row justify-content-center mb-5 pb-3">
        <div class="col-md-7 heading-section ftco-animate text-center">
          <h2 class="mb-4">Where We Are</h2>
          <p>{{ page.location_description }}</p>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-8 offset-sm-2">
          <div class="package-program ftco-animate">
            <div class="d-flex align-self-stretch">
              <div id="map" style="height: 500px;"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section class="ftco-gallery">
    <div class="container-wrap">
      <div class="row no-gutters">
        {% for photo in gallery %}
        <div class="col-md-3 ftco-animate">
          <a href="/photos/" class="gallery img d-flex align-items-center" style="background-image: url({{ photo.photo.url }})">
            <div class="icon mb-4 d-flex align-items-center justify-content-center">
              <span class="">more</span>
            </div>
          </a>
        </div>
        {% endfor %}
      </div>
    </div>
  </section>

  <footer class="ftco-footer ftco-section img" id="footer">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-6 col-md-6">
          <div class="ftco-footer-widget">
            <h2 class="ftco-heading-2">About Us</h2>
            <p>{{ page.footer_about|linebreaksbr }}</p>
          </div>
        </div>
        <div class="col-lg-6">
          <div class="ftco-footer-widget">
            <h2 class="ftco-heading-2">Reach Us</h2>
            <div class="block-23 mb-3">
              <ul>
                <li><span class="icon icon-map-marker"></span><span class="text">Top floor SPK Bldg. Km. 7 Lanang, Davao City </span></li>
                {% for contact in page.contact_set.all %}
                <li><a href="#"><span class="icon icon-phone"></span><span class="text">{{ contact.number }}</span></a></li>
                {% endfor %}
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-12 col-md-12">
          <div class="ftco-footer-widget">
            <ul class="ftco-footer-social list-unstyled float-md-left float-lft">
              <li class="ftco-animate"><a href="https://www.facebook.com/beefitgympluslanang/"><span class="icon-facebook"></span></a></li>
              <!-- <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li> -->
              <!-- <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li> -->
            </ul>
          </div>
        </div>
      </div>
    </div>
  </footer>
{% endblock %}

templates/photos.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <section class="ftco-section" id="packages">
    <div class="container">
      <div class="row justify-content-center mb-5 pb-3">
        <div class="col-md-7 heading-section ftco-animate text-center">
          <h2 class="mb-4">Beefit photos</h2>
        </div>
      </div>
      <div class="row">
        {% for photo in photos %}
        <div class="col-md-6 col-lg-6">
          <div class="package-program ftco-animate">
            <div class="img" style="background-image: url({{ photo.photo.url }})"></div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </section>

  <footer class="ftco-footer ftco-section img" id="footer">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-6 col-md-6">
          <div class="ftco-footer-widget">
            <h2 class="ftco-heading-2">About Us</h2>
            <p>{{ page.footer_about|linebreaksbr }}</p>
          </div>
        </div>
        <div class="col-lg-6">
          <div class="ftco-footer-widget">
            <h2 class="ftco-heading-2">Reach Us</h2>
            <div class="block-23 mb-3">
              <ul>
                <li><span class="icon icon-map-marker"></span><span class="text">Top floor SPK Bldg. Km. 7 Lanang, Davao City </span></li>
                {% for contact in page.contact_set.all %}
                <li><a href="#"><span class="icon icon-phone"></span><span class="text">{{ contact.number }}</span></a></li>
                {% endfor %}
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-12 col-md-12">
          <div class="ftco-footer-widget">
            <ul class="ftco-footer-social list-unstyled float-md-left float-lft">
              <li class="ftco-animate"><a href="https://www.facebook.com/beefitgympluslanang/"><span class="icon-facebook"></span></a></li>
              <!-- <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li> -->
              <!-- <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li> -->
            </ul>
          </div>
        </div>
      </div>
    </div>
  </footer>
{% endblock %}

templates/programs.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="ftco-section" id="programs">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-md-8">
        {% for program in programs %}
        <div class="program d-flex ftco-animate">
          <div class="icon d-flex justify-content-center align-items-center">
            <span class="flaticon-{{ program.icon }}"></span>
          </div>
          <div class="text ml-5">
            <h3>{{ program.title }}</h3>
            <p>{{ program.description|linebreaksbr }}</p>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</section>

  <footer class="ftco-footer ftco-section img" id="footer">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-6 col-md-6">
          <div class="ftco-footer-widget">
            <h2 class="ftco-heading-2">About Us</h2>
            <p>{{ page.footer_about }}</p>
          </div>
        </div>
        <div class="col-lg-6">
          <div class="ftco-footer-widget">
            <h2 class="ftco-heading-2">Reach Us</h2>
            <div class="block-23 mb-3">
              <ul>
                <li><span class="icon icon-map-marker"></span><span class="text">Top floor SPK Bldg. Km. 7 Lanang, Davao City </span></li>
                {% for contact in page.contact_set.all %}
                <li><a href="#"><span class="icon icon-phone"></span><span class="text">{{ contact.number }}</span></a></li>
                {% endfor %}
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-12 col-md-12">
          <div class="ftco-footer-widget">
            <ul class="ftco-footer-social list-unstyled float-md-left float-lft">
              <li class="ftco-animate"><a href="https://www.facebook.com/beefitgympluslanang/"><span class="icon-facebook"></span></a></li>
              <!-- <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li> -->
              <!-- <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li> -->
            </ul>
          </div>
        </div>
      </div>
    </div>
  </footer>
{% endblock %}

templates/rules.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <section class="ftco-section" id="packages">
    <div class="container">
     {% for rule in rules %}      
      <div class="row justify-content-center mb-5 pb-3">
        <div class="col-md-7 heading-section ftco-animate text-center">
          <h2 class="mb-4">{{ rule.title }}</h2>
        </div>
      </div>
      <div class="row">
        {{ rule.rules|linebreaksbr }}
      </div>
    {% endfor %}      
    </div>
  </section>

  <footer class="ftco-footer ftco-section img" id="footer">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-6 col-md-6">
          <div class="ftco-footer-widget">
            <h2 class="ftco-heading-2">About Us</h2>
            <p>{{ page.footer_about|linebreaksbr }}</p>
          </div>
        </div>
        <div class="col-lg-6">
          <div class="ftco-footer-widget">
            <h2 class="ftco-heading-2">Reach Us</h2>
            <div class="block-23 mb-3">
              <ul>
                <li><span class="icon icon-map-marker"></span><span class="text">Top floor SPK Bldg. Km. 7 Lanang, Davao City </span></li>
                {% for contact in page.contact_set.all %}
                <li><a href="#"><span class="icon icon-phone"></span><span class="text">{{ contact.number }}</span></a></li>
                {% endfor %}
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-12 col-md-12">
          <div class="ftco-footer-widget">
            <ul class="ftco-footer-social list-unstyled float-md-left float-lft">
              <li class="ftco-animate"><a href="https://www.facebook.com/beefitgympluslanang/"><span class="icon-facebook"></span></a></li>
              <!-- <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li> -->
              <!-- <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li> -->
            </ul>
          </div>
        </div>
      </div>
    </div>
  </footer>
{% endblock %}